name             'piwik'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures piwik'
long_description 'Installs/Configures piwik'
version          '0.1.0'

depends 'git', '>= 4.3.7'
depends 'composer', '>= 2.2.1'