name             'piwik'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures piwik'
long_description 'Installs/Configures piwik'
version          '0.1.0'

depends 'git', '>= 4.3.7'
depends 'composer', '>= 2.2.1'
depends 'nginx', '>= 2.7.6'
depends 'php', '>= 1.9.0'
depends 'php-fpm'
depends 'mariadb', '>= 0.3.1'
depends 'hostsfile', '>= 2.4.5'
depends 'database', '>= 5.0.0'
depends 'phantomjs', '>= 1.0.3'
depends 'ssh_known_hosts', '~> 3.1.0'
